<!doctype html>
<!--
Design by Free Responsive Templates
http://www.free-responsive-templates.com
Released for free under a Creative Commons Attribution 3.0 Unported License (CC BY 3.0) 
-->
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>test</title>
<link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
<link href='http://fonts.googleapis.com/css?family=Belgrano' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="<?php echo $this->baseUrl('/css/styles.css')?>">
</head>
<body>
<div class="wrapper">
	<header>
    	<div class="logo"><h1><a href="">Test</a></h1></div>
        <nav>
            <ul id="navlist">
                <li id="active"><a href="#">Home</a></li>
                <li><a href="#">About</a></li>
                <li><a href="#">Shop</a></li>
                <li><a href="#">Customers</a></li>
                <li><a href="#">Contact</a></li>
            </ul>
        </nav>
        <div class="clearfloat"></div>
    </header>
    <section>
    	<div class="horSeparator"></div>
    	<h1>test</h1>
        <p>
        <?php echo $this->layout()->content; ?>
        	
        </p>
        <div class="horSeparator"></div>
    </section>
</div>
<footer>
	<p>
        Copyright &copy; Your Company Name. All rights reserved. Designed by <a href="http://www.free-responsive-templates.com" title="free responsive templates">Free Responsive Templates</a>, Validation 
        <a class="footerLink" href="http://validator.w3.org/check/referer" title="This page validates as HTML5"><abbr title="HyperText Markup Language">HTML5</abbr></a> | 
        <a class="footerLink" href="http://jigsaw.w3.org/css-validator/check/referer" title="This page validates as CSS"><abbr title="Cascading Style Sheets">CSS3</abbr></a>
    </p>
</footer>
</body>
</html>
